# dockerfile with cache
FROM fedora:latest

LABEL maintainer Markus Schaeffer <sizufly@gmail.com>

# Base packages and some utilities
RUN dnf -y update && dnf -y install openssh-server passwd procps && dnf clean all

# Create a user “sshuser” and group “sshgroup”
RUN groupadd sshgroup && useradd -ms /bin/bash -g sshgroup zoot

# Create sshuser directory in home
RUN mkdir -p /home/zoot/.ssh

# Intall Keygen
RUN ssh-keygen -A

# Copy the ssh public key in the authorized_keys file.
# The idkey.pub below is a public key file you get from ssh-keygen.
# They are under ~/.ssh directory by default.
COPY id_rsa.pub /home/zoot/.ssh/authorized_keys

# Change ownership of the key file.
RUN chown zoot:sshgroup /home/zoot/.ssh/authorized_keys && chmod 600 /home/zoot/.ssh/authorized_keys

# Create default work dir and change into it
RUN mkdir -p /pkg
WORKDIR /pkg

# Expose docker port 22
EXPOSE 22
RUN rm -rf /run/nologin
CMD ["/usr/sbin/sshd", "-D"]


